name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install bazelisk
        run: |
          brew install bazelisk
      - name: wasm vm build
        run: |
          cd wasm_bazel_example/
          bazelisk build //example:run_wasm
      - name: wasm build
        run: |
          cd tendis_wasm_example/
          bazelisk build //example:optimus_test.wasm
      - name: build wasmedge
        run: |
          eval $(/opt/homebrew/bin/brew shellenv)
          brew install llvm@18 ninja
          git clone https://github.com/WasmEdge/WasmEdge.git -b yiying/fix_aot_oom
          export LLVM_DIR="$(brew --prefix)/opt/llvm@18/lib/cmake"
          export CC=clang
          export CXX=clang++
          cd WasmEdge
          rm -rf build output
          mkdir -p output
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_LINK_LLVM_STATIC=ON -DWASMEDGE_USE_LLVM=On -DCMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/output .
          cmake --build build
          cmake --install build
          ls -alF $GITHUB_WORKSPACE/output/bin
      - name: run aot
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/output/bin"
          cd tendis_wasm_example/
          $GITHUB_WORKSPACE/output/bin/wasmedgec bazel-bin/example/optimus_test.wasm bazel-bin/example/optimus_test.wasm.aot
      - name: test pure wasm
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/output/bin"
          cd tendis_wasm_example/
          ../wasm_bazel_example/bazel-bin/example/run_wasm bazel-bin/example/optimus_test.wasm test ../wasm_bazel_example/100181088_1.bin
      - name: test aot wasm
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/output/bin"
          cd tendis_wasm_example/
          ../wasm_bazel_example/bazel-bin/example/run_wasm bazel-bin/example/optimus_test.wasm.aot test ../wasm_bazel_example/100181088_1.bin
